HW4/WEB/Controllers/DrinkController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net.Http;        // 使用HttpClient類別所屬的名稱空間
using Newtonsoft.Json;        // 使用JsonConvert類別所屬的名稱空間
using Newtonsoft.Json.Linq;
using System.Threading.Tasks; // 使用Task類別所屬的名稱空間
using System.Text;            // 使用Encoding類別所屬的名稱空間
using WEB.Models;


namespace WEB.Controllers
{
    public class DrinkController : Controller
    {

        public async Task<ActionResult> SaveExpenseIndex()
        {
            // 建立一個SaveExpenseViewModel物件
            SaveExpenseModel expenseData = new SaveExpenseModel();

            try
            {
                // 取得消費種類陣列Web API之網址
                string urlGetExpenseTypes = "http://140.137.41.136:1380/A7407630/API/api/WineCupboard";
                //建立HttClient物件
                HttpClient client = new HttpClient();
                // 以非同步GET方式呼叫取得消費種類陣列Web API
                HttpResponseMessage response = await client.GetAsync(urlGetExpenseTypes);
                // 以非同步方式取出回傳結果之JSON格式字串
                string result = await response.Content.ReadAsStringAsync();
                // 將JSON格式字串轉換成.NET的JArray物件 (因為回傳結果為JSON陣列格式字串)
                JArray jsonArray = JArray.Parse(result);
                // 建立一個字串清單物件expenseTypeList
                List<string> expenseTypeList = new List<string>();
                // 將回傳的消費種類一一取出，然後存入字串清單expenseTypeList
                foreach (JObject content in jsonArray.Children<JObject>())
                {
                    expenseTypeList.Add(content.GetValue("expenseType").ToString());
                }
                // 將expenseTypeList存入expenseData物件的expenseTypeList屬性中
                expenseData.expenseTypeList = expenseTypeList;

                // 將expenseData物件傳到View Razor Page
                return View(expenseData);
            }
            catch (Exception ex)
            {
                // 使用TempData的Save變數攜帶儲存消費紀錄發生例外的原因字串
                TempData["Save"] = "儲存消費紀錄時發生例外，原因如下： " + ex.Message;

                // 將expenseTypeList存入expenseData物件的expenseTypeList屬性中
                expenseData.expenseTypeList = new List<string>() { "發生例外!" };

                // 將expenseData物件傳到View Razor Page
                return View(expenseData);
            }
        }

        [HttpPost]
        // 利用Exclude不要自動繫結模型中的result屬性
        public async Task<ActionResult> SaveExpenseIndex([Bind(Exclude = "result")] SaveExpenseModel expenseData)
        {
            try
            {
                // 儲存消費紀錄Web API之網址
                string urlSaveExpense = "http://140.137.41.136:1380/A7407630/API/api/AddDrink/Record";
                //建立HttClient物件
                HttpClient client = new HttpClient();
                // 將expenseData物件序列化成JSON格式字串
                string jsonString = JsonConvert.SerializeObject(expenseData);
                // 建立傳遞內容HttpContent物件，內容格式為application/json
                HttpContent contentPost = new StringContent(jsonString, Encoding.UTF8, "application/json");
                // 以非同步POST方式呼叫儲存消費紀錄Web API
                HttpResponseMessage response = await client.PostAsync(urlSaveExpense, contentPost);
                // 以非同步方式取出回傳結果之JSON格式結果字串
                string result = await response.Content.ReadAsStringAsync();
                // 將JSON格式字串轉換成.NET的JSON物件
                dynamic jsonObject = JsonConvert.DeserializeObject(result);

                // 使用TempData的Save變數攜帶結果字串
                TempData["Save"] = jsonObject.Result;

                //重新導向儲存消費資料頁面
                return RedirectToAction("SaveExpenseIndex");
            }
            catch (Exception ex)  // 例外處理
            {
                // 使用TempData的Result變數攜帶結果字串
                TempData["Save"] = "儲存消費紀錄時發生例外，原因如下: " + ex.Message;

                //重新導向儲存消費資料頁面
                return RedirectToAction("SaveExpenseIndex");
            }
        }

        public ActionResult QueryExpense()
        {
            return View();
        }

        [HttpPost]
        // 利用Exclude不要自動繫結模型中的result屬性
        public async Task<ActionResult> QueryExpense([Bind(Exclude = "result")] QueryExpenseModel queryExpenseData, string btnSend)
        {
            string variety = queryExpenseData.searchType;
            try
            {
                if (btnSend == "查詢酒櫃資料")
                {
                    // 查詢消費紀錄Web API之網址
                    string urlQueryExpense = "http://140.137.41.136:1380/A7407630/API/api/WineCupboard/query/" + variety;
                    //建立HttClient物件
                    HttpClient client = new HttpClient();
                    // 以非同步GET方式呼叫查詢消費紀錄Web API
                    HttpResponseMessage response = await client.GetAsync(urlQueryExpense);
                    // 以非同步方式取出回傳結果之JSON格式字串
                    string result = await response.Content.ReadAsStringAsync();

                    // 將JSON格式字串轉換成.NET的JSON物件
                    dynamic jsonObject = JsonConvert.DeserializeObject(result);

                    // 將查詢消費紀錄頁面之結果字串存入queryExpenseData之result屬性中 
                    queryExpenseData.result = jsonObject.Result;
                }

                //重新導向儲存消費資料頁面
                return View(queryExpenseData);
            }
            catch (Exception ex)  // 例外處理
            {
                // 將查詢消費紀錄發生例外原因字串存入queryExpenseData之result屬性中 
                queryExpenseData.result = "查詢消費紀錄時發生例外，原因如下: " + ex.Message;

                //重新導向儲存消費資料頁面
                return View(queryExpenseData);
            }
        }

        public ActionResult DeleteExpense()
        {
            return View();
        }

        [HttpPost]
        // 利用Exclude不要自動繫結模型中的result屬性
        public async Task<ActionResult> DeleteExpense([Bind(Exclude = "result")] DeleteExpenseModel deleteExpenseData, string btnSend)
        {
            string variety = deleteExpenseData.delType;
            string year = deleteExpenseData.year;
            try
            {
                if (btnSend == "刪除消費資料")
                {
                    // 刪除消費紀錄Web API之網址
                    string urlQueryExpense = "http://140.137.41.136:1380/A7407630/API/api/WineCupboard/delete/" +
                                             variety + "/" + year;
                    //建立HttClient物件
                    HttpClient client = new HttpClient();
                    // 以非同步GET方式呼叫刪除消費紀錄Web API
                    HttpResponseMessage response = await client.GetAsync(urlQueryExpense);
                    // 以非同步方式取出回傳結果之JSON格式字串
                    string result = await response.Content.ReadAsStringAsync();

                    // 將JSON格式字串轉換成.NET的JSON物件
                    dynamic jsonObject = JsonConvert.DeserializeObject(result);

                    // 將查詢消費紀錄頁面之結果字串存入queryExpenseData之result屬性中 
                    deleteExpenseData.result = jsonObject.Result;
                }

                //重新導向儲存消費資料頁面
                return View(deleteExpenseData);
            }
            catch (Exception ex)  // 例外處理
            {
                // 將查詢消費紀錄發生例外原因字串存入queryExpenseData之result屬性中 
                deleteExpenseData.result = "查詢消費紀錄時發生例外，原因如下: " + ex.Message;

                //重新導向儲存消費資料頁面
                return View(deleteExpenseData);
            }
        }

        public async Task<ActionResult> ManageExpenseTypeIndex()
        {
            // 建立一個ManageExpenseTypeViewModel物件
            ManageExpenseTypeModel manageExpenseTypeData = new ManageExpenseTypeModel();

            try
            {
                // 使用GET呼叫Web API
                // 取得所有消費種類格式化字串Web API之網址
                string urlGetAllExpenseTypesString = "http://140.137.41.136:1380/A7407630/API/api/WineCupboard/string/";

                //建立HttClient物件
                HttpClient client = new HttpClient();
                // 以非同步GET呼叫取得所有消費種類格式化字串Web API
                HttpResponseMessage response = await client.GetAsync(urlGetAllExpenseTypesString);
                // 以非同步方式取出回傳結果之JSON格式字串
                string result = await response.Content.ReadAsStringAsync();

                // 將JSON格式字串轉換成.NET的JSON物件
                dynamic jsonObject = JsonConvert.DeserializeObject(result);

                // 使用TempData的Manage變數攜帶要顯示管理消費種類頁面之結果字串
                TempData["Manage"] = jsonObject.Result;

                // 將expenseData物件傳到View Razor Page
                return View(manageExpenseTypeData);
            }
            catch (Exception ex)
            {
                // 使用TempData的Manage變數攜帶管理消費種類發生例外的原因字串
                TempData["Manage"] = "管理消費種類時發生例外，原因如下： " + ex.Message;

                // 將expenseData物件傳到View Razor Page
                return View(manageExpenseTypeData);
            }
        }

        #region 新增消費種類
        //新增消費種類之局部頁面
        public ActionResult AddNewExpenseType()
        {
            //因此頁面用於載入至開始頁面中，故使用部分檢視回傳
            return PartialView();
        }

        // 新增消費種類資料時的Action
        [HttpPost] //設定此Action只接受頁面POST資料傳入
        //使用Bind的Include來定義只接受的欄位，用來避免傳入其他不相干值
        public async Task<ActionResult> AddNewExpenseType([Bind(Include = "expenseType")] ManageExpenseTypeModel manageExpenseTypeData)
        {
            try
            {
                // 新增消費種類Web API之網址
                string urlAddNewExpenseType = "http://140.137.41.136:1380/A7407630/API/api/AddDrink/Type";

                //建立HttClient物件
                HttpClient client = new HttpClient();
                // 將manageExpenseTypeData物件序列化成JSON格式字串
                string jsonString = JsonConvert.SerializeObject(manageExpenseTypeData);
                // 建立傳遞內容HttpContent物件，內容格式為application/json
                HttpContent contentPost = new StringContent(jsonString, Encoding.UTF8, "application/json");
                // 以非同步POST方式呼叫新增消費種類Web API
                HttpResponseMessage response = await client.PostAsync(urlAddNewExpenseType, contentPost);
                // 以非同步方式取出回傳結果之JSON格式字串

HW4/WEB/Views/Drink/AddNewExpenseType.cshtml
@model WEB.Models.ManageExpenseTypeModel

@*建立新增消費種類表單*@
@using (Html.BeginForm("AddNewExpenseType", "Drink", FormMethod.Post))
{
    <table>
        <tr>
            <td>
                @Html.LabelFor(m => m.expenseType, new { @class = "label label-primary" })
            </td>
            <td>
                @Html.TextBoxFor(m => m.expenseType)
                @Html.ValidationMessageFor(m => m.expenseType, "", new { @class = "text-danger" })
                <input type="submit" name="btnSend" value="新增" class="btn btn-success">
            </td>
        </tr>
    </table>
}

HW4/WEB/Views/Drink/DeleteExpense.cshtml
@model WEB.Models.DeleteExpenseModel

@{
    ViewBag.Title = "刪除酒櫃紀錄頁面";
}

<style>
    .button {
        border: none;
        background-color: transparent;
        padding: 8px 16px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: 14px;
        margin: 4px 2px;
        transition-duration: 0.4s;
        cursor: pointer;
    }

    .button1 {
        background-color: transparent;
        color: white;
        border: 2px solid #4CAF50;
    }

    .button1:hover {
        background-color: #4CAF50;
        color: white;
    }
</style>

<div align="center" style="font-family:標楷體">
    <br />
    <b class="label label-danger" style="font-size:x-large">刪除酒櫃紀錄操作介面</b>
    <br />
    <br />

    @*建立儲存酒櫃紀錄表單*@
    @using (Html.BeginForm("DeleteExpense", "Drink"))
    {
        <table>
            <tr>
                <td>
                    @Html.LabelFor(m => m.delType, new { @class = "label label-primary" })
                </td>
                <td>
                    @Html.TextBoxFor(m => m.delType)
                    @Html.ValidationMessageFor(m => m.delType, "", new { @class = "text-danger" })
                </td>
            </tr>
            <tr>
                <td>
                    @Html.LabelFor(m => m.year, new { @class = "label label-primary" })
                </td>
                <td>
                    @Html.TextBoxFor(m => m.year)
                    @Html.ValidationMessageFor(m => m.year, "", new { @class = "text-danger" })
                </td>
            </tr>

        </table>
        <input type="submit" name="btnSend" value="刪除消費資料" class="btn btn-success">
        <br />
        if (TempData["Delete"] == null)
        {
            @Html.TextArea("Result", null, 10, 100, htmlAttributes: new { style = "width: 50%; max-width: 100%;" })
        }
        else
        {
            @Html.TextArea("Result", TempData["Delete"].ToString(), 10, 100, htmlAttributes: new { style = "width: 50%; max-width: 100%;" })
        }
        <br />

        @Html.ActionLink("儲存酒櫃紀錄頁面", "SaveExpenseIndex", "Drink", null, new { @class = "button button1" }) <span>&nbsp;</span>
        @Html.ActionLink("查詢酒櫃紀錄頁面", "QueryExpense", "Drink", null, new { @class = "button button1" }) <span>&nbsp;</span>
        @Html.ActionLink("管理酒櫃種類頁面", "ManageExpenseTypeIndex", "Drink", null, new { @class = "button button1" })
    }
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

HW4/WEB/Views/Drink/DeleteExpenseType.cshtml
@model WEB.Models.ManageExpenseTypeModel

@*建立刪除消費種類表單*@
@using (Html.BeginForm("DeleteExpenseType", "Drink"))
{
    <table>
        <tr>
            <td>
                @Html.LabelFor(m => m.expenseTypeNumber, new { @class = "label label-primary" })
            </td>
            <td>
                @Html.TextBoxFor(m => m.expenseTypeNumber)
                @Html.ValidationMessageFor(m => m.expenseTypeNumber, "", new { @class = "text-danger" })
                <input type="submit" name="btnSend" value="刪除" class="btn btn-success">
            </td>
        </tr>
    </table>
}

HW4/WEB/Views/Drink/ManageExpenseTypeIndex.cshtml
@{
    ViewBag.Title = "管理酒櫃種類頁面";
}

<style>
    .button {
        border: none;
        background-color: transparent;
        padding: 8px 16px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: 14px;
        margin: 4px 2px;
        transition-duration: 0.4s;
        cursor: pointer;
    }

    .button1 {
        background-color: transparent;
        color: white;
        border: 2px solid #4CAF50;
    }

        .button1:hover {
            background-color: #4CAF50;
            color: white;
        }
</style>

<div align="center" style="font-family:標楷體">
    <br />
    <b class="label label-danger" style="font-size:x-large">管理酒櫃種類操作介面</b>
    <br />
    <br />
    @*載入新增消費種類頁面*@
    <div id="AddNewExpenseType">
        @Html.Action("AddNewExpenseType")
    </div>

    @*載入刪除消費種類頁面*@
    <div id="DeleteExpenseType">
        @Html.Action("DeleteExpenseType")
    </div>

    @if (TempData["Manage"] == null)
    {
        @Html.TextArea("Result", null, 16, 100, htmlAttributes: new { style = "width: 50%; max-width: 100%;" })
    }
    else
    {
        @Html.TextArea("Result", TempData["Manage"].ToString(), 16, 100, htmlAttributes: new { style = "width: 50%; max-width: 100%;" })
    }

    <br />

    @Html.ActionLink("儲存酒櫃紀錄頁面", "SaveExpenseIndex", "Drink", null, new { @class = "button button1" })  <span>&nbsp;</span>
    @Html.ActionLink("查詢酒櫃紀錄頁面", "QueryExpense", "Drink", null, new { @class = "button button1" }) <span>&nbsp;</span>
    @Html.ActionLink("刪除酒櫃紀錄頁面", "DeleteExpense", "Drink", null, new { @class = "button button1" })
</div>

HW4/WEB/Views/Drink/QueryExpense.cshtml
@model WEB.Models.QueryExpenseModel

@{
    ViewBag.Title = "查詢酒櫃紀錄頁面";
}

<style>
    .button {
        border: none;
        background-color: transparent;
        padding: 8px 16px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: 14px;
        margin: 4px 2px;
        transition-duration: 0.4s;
        cursor: pointer;
    }

    .button1 {
        background-color: transparent;
        color: white;
        border: 2px solid #4CAF50;
    }

    .button1:hover {
        background-color: #4CAF50;
        color: white;
    }
</style>


<div align="center" style="font-family:標楷體">
    <br />
    <b class="label label-danger" style="font-size:x-large">查詢酒櫃紀錄操作介面</b>
    <br />
    <br />

    @*建立儲存酒櫃紀錄表單*@
    @using (Html.BeginForm("QueryExpense", "Drink"))
    {
        <table>
            <tr>
                <td>
                    @Html.LabelFor(m => m.searchType, new { @class = "label label-primary" })
                </td>
                <td>
                    @Html.TextBoxFor(m => m.searchType)
                    @Html.ValidationMessageFor(m => m.searchType, "", new { @class = "text-danger" })
                </td>
            </tr>
        </table>
        <input type="submit" name="btnSend" value="查詢酒櫃資料" class="btn btn-success">
        <br />
        if (TempData["Query"] == null)
        {
            @Html.TextArea("Result", null, 10, 100, htmlAttributes: new { style = "width: 50%; max-width: 100%;" })
        }
        else
        {
            @Html.TextArea("Result", TempData["Query"].ToString(), 10, 100, htmlAttributes: new { style = "width: 50%; max-width: 100%;" })
        }
        <br />

        @Html.ActionLink("儲存酒櫃紀錄頁面", "SaveExpenseIndex", "Drink", null, new { @class = "button button1" }) <span> &nbsp;</span>
        @Html.ActionLink("刪除酒櫃紀錄頁面", "DeleteExpense", "Drink", null, new { @class = "button button1" }) <span> &nbsp;</span>
        @Html.ActionLink("管理酒櫃種類頁面", "ManageExpenseTypeIndex", "Drink", null, new { @class = "button button1" })
    }
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

HW4/WEB/Views/Drink/SaveExpenseIndex.cshtml
@model WEB.Models.SaveExpenseModel

@{
    ViewBag.Title = "儲存酒櫃紀錄頁面";
}

<style>
    .button {
        border: none;
        background-color: transparent;
        padding: 8px 16px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: 14px;
        margin: 4px 2px;
        transition-duration: 0.4s;
        cursor: pointer;
    }

    .button1 {
        background-color: transparent;
        color: white;
        border: 2px solid #4CAF50;
    }

    .button1:hover {
        background-color: #4CAF50;
        color: white;
    }
</style>

@* 從Model中取出酒櫃種類陣列，據以建立酒櫃種類下拉式選項清單物件 *@
@{
    List<SelectListItem> expenseTypeListItems = new List<SelectListItem>();
    foreach (string k in Model.expenseTypeList)
    {
        expenseTypeListItems.Add(new SelectListItem { Text = k });
    }
}

<div align="center" style="font-family:標楷體">
    <br />
    <b class="label label-danger" style="font-size:x-large">儲存酒櫃紀錄操作介面</b>
    <br />
    <br />

    @*建立儲存酒櫃紀錄表單*@
    @using (Html.BeginForm("SaveExpenseIndex", "Drink", FormMethod.Post))
    {
        <table>
            <tr>
                <td>
                    @Html.LabelFor(m => m.expenseType, new { @class = "label label-primary label-lg" })
                </td>
                <td>
                    @Html.DropDownListFor(m => m.expenseType, expenseTypeListItems, "選擇酒的種類", new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.expenseType, "", new { @class = "text-danger" })
                </td>
            </tr>
            <tr>
                <td>
                    @Html.LabelFor(m => m.year, new { @class = "label label-primary label-lg" })
                </td>
                <td>
                    @Html.EditorFor(m => m.year)
                    @Html.ValidationMessageFor(m => m.year, "", new { @class = "text-danger" })
                </td>
            </tr>
        </table>
        <input type="submit" name="btnSaveExpense" value="儲存" class="btn btn-success">
        <br />
        if (TempData["Save"] == null)
        {
            @Html.TextArea("Result", null, 8, 100, htmlAttributes: new { style = "width: 50%; max-width: 100%;" })
        }
        else
        {
            @Html.TextArea("Result", TempData["Save"].ToString(), 8, 100, htmlAttributes: new { style = "width: 50%; max-width: 100%;" })
        }
        <br />

        @Html.ActionLink("查詢酒櫃紀錄頁面", "QueryExpense", "Drink", null, new { @class = "button button1" }) <span> &nbsp;</span>
        @Html.ActionLink("刪除酒櫃紀錄頁面", "DeleteExpense", "Drink", null, new { @class = "button button1" }) <span> &nbsp;</span>
        @Html.ActionLink("管理酒櫃種類頁面", "ManageExpenseTypeIndex", "Drink", null, new { @class = "button button1" })
    }
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}