HW3/cloudHW03Web/Models/ConstellationModels.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace cloudHW03Web.Models
{
    public class ConstellationModels
    {
        [DisplayName("月份：")]
        [Required(ErrorMessage = "請輸入月份")]
        public double Month { get; set; }

        [DisplayName("日期：")]
        [Required(ErrorMessage = "請輸入日期")]
        public double Day { get; set; }

        [DisplayName("結果：")]
        public string Result { get; set; }
    }
}

HW3/cloudHW03Web/Models/FibonacciModels.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace cloudHW03Web.Models
{
    public class FibonacciModels
    {
        [DisplayName("數字：")]
        [Required(ErrorMessage = "請輸入數字")]
        public double Number { get; set; }

        [DisplayName("結果：")]
        public string Result { get; set; }
    }
}

HW3/cloudHW03Web/Controllers/ConstellationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using System.Net.Http; // needed for using the HttpClient class
using System.Net.Http.Headers;
using System.Threading.Tasks;

using cloudHW03Web.Models;
using Newtonsoft.Json;
using System.Text;

namespace cloudHW03Web.Controllers
{
    public class ConstellationController : Controller
    {
        // 由App_Start資料夾中的靜態類別WebApiConfig.cs取出WebApis的基底網址(自己定義的)
        readonly string baseurl = WebApiConfig.baseurl;

        // GET  URL: http://.../Constellation/ConstellationGet
        public ActionResult ConstellationGet()
        {
            return View();
        }

        // POST  URL: http://.../math/mathcompute
        [HttpPost]
        // 只要自動繫結模型中的Month及Day
        public async Task<ActionResult> ConstellationGet([Bind(Include = "Month, Day")] ConstellationModels mathdata, string btnCompute)
        {
            if (!ModelState.IsValid)
            {
                return View(mathdata);
            }
            try
            {
                string urlstring = baseurl + "api/constellationcompute/" + mathdata.Month + "/" + mathdata.Day;
                //建立HttClient物件
                HttpClient client = new HttpClient();
                // 以非同步GET方式呼叫數學服務之API
                var response = await client.GetAsync(urlstring);
                // 以非同步方式取出回傳結果之JSON格式字串
                string result = await response.Content.ReadAsStringAsync();
                // 將JSON格式字串轉換成.NET的JSON物件
                dynamic jsonObject = JsonConvert.DeserializeObject(result);
                // 從JSON物件中取出Result的值，存入mathdata物件的Result欄位
                mathdata.Result = jsonObject.Result;
                // 將mathdata物件傳送到View顯示
                return View(mathdata);
            }
            catch (Exception ex)
            {
                mathdata.Result = "數學運算時發生例外，原因如下: " + ex.Message;
                // 將mathdata物件傳送到View顯示
                return View(mathdata);
            }

        }
    }
    public class RequestDataForConstellationComputePost
    {
        public double month { get; set; }
        public double day { get; set; }
    }
}

HW3/cloudHW03Web/Controllers/FibonacciController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using System.Net.Http; // needed for using the HttpClient class
using System.Net.Http.Headers;
using System.Threading.Tasks;

using cloudHW03Web.Models;
using Newtonsoft.Json;
using System.Text;

namespace cloudHW03Web.Controllers
{
    public class FibonacciController : Controller
    {
        readonly string baseurl = WebApiConfig.baseurl;

        // GET: URL: http://.../Fibonacci/fibonacciPost
        public ActionResult FibonacciPost()
        {
            return View();
        }

        [HttpPost]
        // 只要自動繫結模型中的number
        public async Task<ActionResult> fibonacciPost([Bind(Include = "Number")] FibonacciModels mathdata, string btnCompute)
        {
            if (!ModelState.IsValid)
            {
                return View(mathdata);
            }
            try
            {
                string urlstring = baseurl + "api/Fibonacci/";//FibonacciPost
                //建立HttClient物件
                HttpClient client = new HttpClient();
                // // 建立JSON格式之請求內容字串
                RequestDataForFibonacciComputePost requestData = new RequestDataForFibonacciComputePost();
                requestData.number = mathdata.Number;
                string jsonString = JsonConvert.SerializeObject(requestData);
                // 建立傳遞內容HttpContent物件
                HttpContent httpContent = new StringContent(jsonString, Encoding.UTF8, "application/json");
                // 以非同步POST方式呼叫數學服務之Web API
                var response = await client.PostAsync(urlstring, httpContent);
                // 以非同步方式取出回傳結果之JSON格式字串
                string result = await response.Content.ReadAsStringAsync();
                // 將JSON格式字串轉換成.NET的JSON物件
                dynamic jsonObject = JsonConvert.DeserializeObject(result);
                // 從JSON物件中取出Result的值，存入mathdata物件的Result欄位
                mathdata.Result = jsonObject.Result;
                // 將mathdata物件傳送到View顯示
                return View(mathdata);
            }
            catch (Exception ex)
            {
                mathdata.Result = "費氏數列運算時發生例外，原因如下: " + ex.Message;
                // 將mathdata物件傳送到View顯示
                return View(mathdata);
            }

        }
    }

    public class RequestDataForFibonacciComputePost
    {
        public double number { get; set; }
    }
}

HW3/cloudHW03Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace cloudHW03Web.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

HW3/cloudHW03Web/Views/Constellation/ConstellationGet.cshtml
@model cloudHW03Web.Models.ConstellationModels

@{
    ViewBag.Title = "星座查詢服務";
}



<div align="center">
    <br />
    <b class="label label-danger" style="font-size:x-large">呼叫星座查詢服務 by GET</b>
    <br /> <br />
    @*建立星座查詢服務表單*@
    @using (Html.BeginForm("ConstellationGet", "Constellation"))
    {
        <table>
            <tr>
                <td>
                    @Html.LabelFor(model => model.Month, new { @class = "label label-warning" })
                </td>
                <td>
                    @Html.TextBoxFor(model => model.Month)
                    @Html.ValidationMessageFor(model => model.Month, "", new { @class = "text-danger" })
                </td>
            </tr>
            <tr>
                <td>
                    @Html.LabelFor(model => model.Day, new { @class = "label label-warning" })
                </td>
                <td>
                    @Html.TextBoxFor(model => model.Day)
                    @Html.ValidationMessageFor(model => model.Day, "", new { @class = "text-danger" })
                </td>
            </tr>
            <tr>
                <td>
                    @Html.LabelFor(model => model.Result, new { @class = "label label-warning" })
                </td>
                <td>
                    @Html.TextBoxFor(model => model.Result)
                </td>
            </tr>
        </table>
        <input type="submit" name="btnCompute" value="查詢" class="btn btn-success">
    }
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

HW3/cloudHW03Web/Views/Fibonacci/FibonacciPost.cshtml
@model cloudHW03Web.Models.FibonacciModels

@{
    ViewBag.Title = "費氏數列計算服務";
}



<div align="center">
    <br />
    <b class="label label-danger" style="font-size:x-large">呼叫費氏數列計算服務 by POST</b>
    <br /> <br />
    @*建立費氏數列計算服務表單*@
    @using (Html.BeginForm("FibonacciPost", "Fibonacci"))
    {
        <table>
            <tr>
                <td>
                    @Html.LabelFor(model => model.Number, new { @class = "label label-warning" })
                </td>
                <td>
                    @Html.TextBoxFor(model => model.Number)
                    @Html.ValidationMessageFor(model => model.Number, "", new { @class = "text-danger" })
                </td>
            </tr>
            <tr>
                <td>
                    @Html.LabelFor(model => model.Result, new { @class = "label label-warning" })
                </td>
                <td>
                    @Html.TextBoxFor(model => model.Result)
                </td>
            </tr>
        </table>
        <input type="submit" name="btnCompute" value="計算" class="btn btn-success">
    }
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}